version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nexus_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: nexus_db
    ports:
      - "5432:5432"
    volumes:
      - nexus_pgdata:/var/lib/postgresql/data

volumes:
  nexus_pgdata:
